'use client'; import { useState } from 'react'; import { motion, AnimatePresence } from 'framer-motion'; import { useSound } from '@/hooks/useSound'; import './Bookshelf.css';
interface Book { id: string; title: string; author: string; color: string; spine: string; category: 'vastu'|'numerology'; description: string; }
const books: Book[] = [
  { id:'mayamatam', title:'Mayamatam', author:'Maya', color:'#8B5A2B', spine:'#5C3A1E', category:'vastu', description:'Ancient treatise on Vastu architecture.' },
  { id:'brihat-samhita', title:'Brihat Samhita', author:'Varahamihira', color:'#C88A5D', spine:'#A06A3D', category:'vastu', description:'Encyclopedic work on Vastu and astrology.' },
  { id:'cheiro-numbers', title:'Book of Numbers', author:'Cheiro', color:'#1985A1', spine:'#0D5A70', category:'numerology', description:'Classic work on numerology.' },
];
function BookCard({ book, onClick }: { book: Book; onClick: () => void }) { const { play } = useSound(); return (<motion.div className="book-card" style={{ '--book-color': book.color, '--spine-color': book.spine } as React.CSSProperties} whileHover={{ y: -10, scale: 1.02 }} onClick={() => { onClick(); play('clickSecondary'); }}><div className="book-cover"><span className="book-emoji">{book.category==='vastu'?'🕉️':'🔢'}</span><h3 className="book-title">{book.title}</h3><p className="book-author">{book.author}</p></div><div className="book-spine"></div></motion.div>); }
function BookReader({ book, onClose }: { book: Book; onClose: () => void }) { const [currentPage, setCurrentPage] = useState(0); const pages = [`Introduction to ${book.title}`, book.description]; const { play } = useSound(); return (<motion.div initial={{ opacity:0, scale:0.9 }} animate={{ opacity:1, scale:1 }} exit={{ opacity:0 }} className="book-reader-modal"><div className="book-reader-content"><button className="close-btn" onClick={onClose}>✕</button><div className="book-reader-pages"><div className="page left-page"><h3>{book.title}</h3><p>{pages[currentPage]}</p></div><div className="page right-page"><h3>{book.author}</h3><p>{pages[currentPage+1]||''}</p></div></div><div className="reader-controls"><button onClick={()=>{ if(currentPage>0) setCurrentPage(currentPage-1); play('clickSecondary'); }} disabled={currentPage===0}>←</button><span>{currentPage+1}/{pages.length}</span><button onClick={()=>{ if(currentPage<pages.length-2) setCurrentPage(currentPage+1); play('clickSecondary'); }} disabled={currentPage>=pages.length-2}>→</button></div><button onClick={onClose} className="back-shelf-btn">Back to Shelf</button></div></motion.div>); }
export function Bookshelf3D() { const [selectedBook, setSelectedBook] = useState<Book|null>(null); return (<div className="bookshelf-wrapper"><div className="bookshelf-grid">{books.map(b=><BookCard key={b.id} book={b} onClick={()=>setSelectedBook(b)} />)}</div><AnimatePresence>{selectedBook && <BookReader book={selectedBook} onClose={()=>setSelectedBook(null)} />}</AnimatePresence></div>); }
export default Bookshelf3D;
